### ISSUE TITLE
Backend. Неправильные данные в заказе

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#64]
Заказ сохраняется с не правильными данными в поле
- phone

#### POST /v1/orders/create
<table><tr><th>Запрос</th><th>Ответ</th><tr>
<tr><td>
<pre lang="json">
{
	"price_id": "1",
	"pet_name": "Dog",
	"gender": "m",
	"size": "1",
	"breed": "Dog",
	"birthday_date": "2000-12-01",
	"birthday_years": "0-1",
	"food_exceptions": "Fish",
	"user_name": "Ivan",
	"email": "covexif854@gilfun.com",
	"phone": 9153134300,
	"address": "Moscow",
	"date_delivery": "2020-01-01",
	"time_delivery": "21:45"
}
</pre>
</td>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "id": 161
  }
}
</pre>
</td></tr>
</table>

#### GET /v1/orders
<table>
<tr>
<th>Ответ</th>
<tr>
<tr>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "orders": [
      {
        "id": 161,
        "phone": 2147483647,
        ...
      }
    ]
  }
}
</pre>
</td>
</tr>
</table>

**Comment by DABronskikh** [comment]
поправил
