### ISSUE TITLE
Backend. При заказе добавляется пользователь с не правильными данными

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#65]
При заказе добавляется пользователь с не правильными данными в полях
- phone
- address

#### POST /v1/order/create
<table><tr><th>Запрос</th><th>Ответ</th><tr>
<tr><td>
<pre lang="json">
{
	"price_id": "1",
	"pet_name": "Dog",
	"gender": "m",
	"size": "1",
	"breed": "Dog",
	"birthday_date": "2000-12-01",
	"birthday_years": "0-1",
	"food_exceptions": "Fish",
	"user_name": "Ivan",
	"email": "covexif854@gilfun.com",
	"phone": 9153134300,
	"address": "Moscow",
	"date_delivery": "2020-01-01",
	"time_delivery": "21:45"
}
</pre>
</td>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "id": 161
  }
}
</pre>
</td></tr>
</table>

#### GET /v1/user
<table>
<tr>
<th>Ответ</th>
<tr>
<tr>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "email": "covexif854@gilfun.com",
    "name": "Ivan",
    "phone": 2147483647,
    "address": null,
    "is_admin": 0
  }
}
</pre>
</td>
</tr>
</table>

**Comment by DABronskikh** [comment]
поправил
