### ISSUE TITLE
Backend. При заказе добавляется питомец с null полями

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#66]
При заказе добавляется питомец с null полями
- birthday_date
- birthday_years
- food_exceptions

#### POST /v1/order/create
<table><tr><th>Запрос</th><th>Ответ</th><tr>
<tr><td>
<pre lang="json">
{
	"price_id": "1",
	"pet_name": "Dog",
	"gender": "m",
	"size": "1",
	"breed": "Dog",
	"birthday_date": "2000-12-01",
	"birthday_years": "0-1",
	"food_exceptions": "Fish",
	"user_name": "Ivan",
	"email": "covexif854@gilfun.com",
	"phone": 9153134300,
	"address": "Moscow",
	"date_delivery": "2020-01-01",
	"time_delivery": "21:45"
}
</pre>
</td>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "id": 161
  }
}
</pre>
</td></tr>
</table>

#### GET /v1/orders
<table>
<tr>
<th>Ответ</th>
<tr>
<tr>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "orders": [
      {
        "id": 161,
        "pet_id": 130,
        ...
      }
    ]
  }
}
</pre>
</td>
</tr>
</table>

#### GET /v1/pets
<table>
<tr>
<th>Ответ</th>
<tr>
<tr>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "pets": [
      {
        "id": 130,
        "name": "Dog",
        "gender": "m",
        "size": "1",
        "breed": "Dog",
        "birthday_date": null,
        "birthday_years": null,
        "food_exceptions": null
      }
    ]
  }
}
</pre>
</td>
</tr>
</table>

**Comment by DABronskikh** [comment]
Поправил

**Comment by DABronskikh** [comment]
поправил
