### ISSUE TITLE
Backend. Не работает обновление данных пользователя

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#68]
Не обновляются поля phone и address

#### POST /v1/user/update
<table>
<tr>
<th>Запрос</th>
<th>Ответ</th>
<tr>
<tr>
<td>
<pre lang="json">
{
    "email": "covexif854@gilfun.com",
    "name": "Vova",
    "phone": 9123000123,
    "address": "London"
}
</pre>
</td>
<td>
<pre lang="json">
{
  "status": 1,
  "data": true
}
</pre>
</td>
</tr>
</table>

#### GET /v1/user
<table>
<tr>
<th>Было</th>
<th>Стало</th>
<tr>
<tr>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "email": "covexif854@gilfun.com",
    "name": "Ivan",
    "phone": 2147483647,
    "address": null,
    "is_admin": 0
  }
}
</pre>
</td>
<td>
<pre lang="json">
{
  "status": 1,
  "data": {
    "email": "covexif854@gilfun.com",
    "name": "Vova",
    "phone": 2147483647,
    "address": null,
    "is_admin": 0
  }
}
</pre>
</td>
</tr>
</table>

**Comment by DABronskikh** [comment]
Поправил
