### ISSUE TITLE
Backend. Заказы по запросу админа

### ISSUE THREAD

**Issue by widetrace** [DABronskikh/f-ZooBro#71]
Запрашиваю с заказом и питомца, там пол вместо стандартного `f` и `m`, стало `w` и `m`. 
Либо везде `f` и `m`, либо везде `w` и `m`.

**Comment by DABronskikh** [comment]
Предлагаю валидировать 2 значения w и m
а все тестовые заказы будут удалены

**Comment by widetrace** [comment]
Итог, будем w/m или f/m?

**Comment by DABronskikh** [comment]
теперь все w/m

**Comment by DABronskikh** [comment]
админка переезжает на бэк)
