### ISSUE TITLE
Backend. Не работает обновление данных питомца

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#74]
Не обновляются поля у питомца
- size
- birthday_date

#### POST /v1/pets/update
<table>
<tr>
<th>Запрос</th><th>Ответ</th>
</tr>
<tr>
<td><pre lang="json">
{
	"id": 139,
	"name": "Белка",
	"gender": "w",
	"size": "2",
	"breed": "Метис",
	"birthday_date": "2008-12-01",
	"birthday_years": "0-1",
	"food_exceptions": "Курица"
}
</pre></td>
<td><pre lang="json">
{
  "status": 1,
  "data": true
}
</pre></td>
</tr>
</table>

#### GET /v1/pets
<table>
<tr>
<th>Было</th>
<th>Стало</th>
</tr>
<tr>
<td><pre lang="json">
{
  "status": 1,
  "data": {
    "pets": [
      {
        "id": 139,
        "name": "Пушок",
        "gender": "m",
        "size": "1",
        "breed": "Дворняга",
        "birthday_date": "2000-12-01",
        "birthday_years": "1-5",
        "food_exceptions": "Рыба"
      }
    ]
  }
}
</pre></td>
<td><pre lang="json">
{
  "status": 1,
  "data": {
    "pets": [
      {
        "id": 139,
        "name": "Белка",
        "gender": "w",
        "size": "1",
        "breed": "Метис",
        "birthday_date": "2000-12-01",
        "birthday_years": "0-1",
        "food_exceptions": "Курица"
      }
    ]
  }
}
</pre></td>
</tr>
</table>

**Comment by DABronskikh** [comment]
Поправил
