### ISSUE TITLE
Backend. Питомец добавляется без даты рождения (birthday_date == null)

### ISSUE THREAD

**Issue by mnick91311** [DABronskikh/f-ZooBro#79]
#### POST /v1/pets
<table><tr>
<th>Запрос</th>
<th>Ответ</th>
</tr><tr>
<td><pre lang="json">
{
	"name": "Пушок",
	"gender": "m",
	"size": "2",
	"breed": "Боксер",
	"birthday_date": "2020-02-02",
	"birthday_years": "0-1",
	"food_exceptions": "Курица"
}
</pre></td>
<td><pre lang="json">
{
  "status": 1,
  "data": {
    "id": 160
  }
}
</pre></td>
</tr></table>

#### GET /v1/pets
<table><tr>
<th>Ответ</th>
</tr><tr>
<td><pre lang="json">
{
  "status": 1,
  "data": {
    "pets": [
      ...
      {
        "id": 160,
        "name": "Пушок",
        "gender": "m",
        "size": "2",
        "breed": "Боксер",
        "birthday_date": null,
        "birthday_years": "0-1",
        "food_exceptions": "Курица"
      }
    ]
  }
}
</pre></td>
</tr></table>

**Comment by DABronskikh** [comment]
Поправил
